#!/usr/bin/env python3

import os, sys

cli_script_dir = os.path.abspath(os.path.dirname(os.path.realpath(__file__)))
if cli_script_dir not in sys.path: sys.path.append(cli_script_dir)

if 'SERVER_URL' not in os.environ: os.environ['SERVER_URL'] = 'http://jupiter.apama.com:5000'

if __name__ == "__main__":
	import apm
	apm.main()
